filmweb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', RedirectView.as_view(url='movies/')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path

from movies import views

urlpatterns = [
    path('', views.index, name='index'),
    path('films/', views.FilmListView.as_view(), name='film_list'),
    path('films/<int:pk>/', views.FilmDetailView.as_view(), name='film_detail'),
    path('films/genres/<str:genre_name>/', views.FilmListView.as_view(), name='film_genre'),
    path('topten', views.topten, name='topten'),
]

movies/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse


def attachment_path(instance, filename):
    """ Metoda vrací cestu k uploadovaným souborů - přílohám filmů.
        Cesta má obecnou podobu: film/id-filmu/attachments/nazev-souboru.
        Parametr instance odkazuje na instanci (objekt) filmu.
        Parametr filename obsahuje název uploadovaného souboru. """
    return "film/" + str(instance.film.id) + "/attachments/" + filename


def poster_path(instance, filename):
    """ Metoda vrací cestu k uploadovanému plakátu. """
    return "film/" + str(instance.id) + "/poster/" + filename


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Genre name",
                            help_text='Enter a film genre (e.g. sci-fi, comedy)')

    class Meta:
        # atribut ordering definuje upřednostňovaný způsob řazení - zde vzestupně podle pole/sloupce name
        ordering = ["name"]

    def __str__(self):
        """ Řetězec, který se používá jako textová reprezentace objektu (například v administraci aplikace).
        V našem případě bude objekt (žánr) reprezentován výpisem obsahu pole name """
        return self.name

    def film_count(self, obj):
        return obj.film_set.count()


class Film(models.Model):
    # Fields
    # Znakové pole o maximální délce 200 znaků pro vložení názvu filmu
    title = models.CharField(max_length=200, verbose_name="Title")
    # Textové pole pro vložení delšího textu popisujícího děj filmu
    # Formulářový prvek může zůstat prázdný - parametry blank=True, null=True
    plot = models.TextField(blank=True, null=True, verbose_name="Plot")
    # Pole obsahuje datum uvedení filmu, které musí být zadáno v náležitém tvaru (YYYY-MM-DD); nepovinný údaj
    release_date = models.DateField(blank=True, null=True,
                                    help_text="Please use the following format: <em>YYYY-MM-DD</em>.",
                                    verbose_name="Release date")
    # Celočíselné pole pro nepovinné zadání stopáže (délky) filmu v minutách
    runtime = models.IntegerField(blank=True, null=True,
                                  help_text="Please enter an integer value (minutes)",
                                  verbose_name="Runtime")
    # Pole pro zadání desetinného čísla vyjadřujícího hodnocení filmu v rozsahu 1.0 až 10.0
    # Výchozí hodnota je nastavena na 5.0
    # K validaci hodnot jsou použity metody z balíku/knihovny django.core.validators
    rate = models.FloatField(default=5.0,
                             validators=[MinValueValidator(1.0), MaxValueValidator(10.0)],
                             null=True, help_text="Please enter an float value (range 1.0 - 10.0)",
                             verbose_name="Rate")
    # Pole typu image, které umožňuje upload obrázku s plakátem filmu
    poster = models.ImageField(upload_to=poster_path, blank=True, null=True, verbose_name="Poster")
    # Vytvoří vztah mezi modely Film a Genre typu M:N
    genres = models.ManyToManyField(Genre, help_text='Select a genre for this film')

    # Metadata
    class Meta:
        # Záznamy budou řazeny primárně sestupně (znaménko mínus) podle data uvedení,
        # sekundárně vzestupně podle názvu
        ordering = ["-release_date", "title"]

    # Methods
    def __str__(self):
        """Součástí textové reprezentace filmu bude jeho název, rok uvedení a hodnocení"""
        return f"{self.title}, year: {str(self.release_date.year)}, rate: {str(self.rate)}"

    def get_absolute_url(self):
        """Metoda vrací URL stránky, na které se vypisují podrobné informace o filmu"""
        return reverse('film-detail', args=[str(self.id)])

    def release_year(self):
        return self.release_date.year

    def rate_percent(self):
        return format_html("{} %", int(self.rate * 10))


class Attachment(models.Model):
    """Třída Attachment je modelem pro databázový objekt (tabulku), který bude obsahovat údaje o přílohách filmů"""
    # Fields
    # Povinný titulek přílohy - text do délky 200 znaků
    title = models.CharField(max_length=200, verbose_name="Title")
    # Časový údaj o poslední aktualizaci přílohy - automaticky se ukládá aktuální čas
    last_update = models.DateTimeField(auto_now=True)
    # Pole pro upload souboru
    # Parametr upload_to zajistí uložení souboru do složky specifikované v návratové hodnotě metody attachment_path
    file = models.FileField(upload_to=attachment_path, null=True, verbose_name="File")

    # Konstanta, v níž jsou ve formě n-tic (tuples) předdefinovány různé typy příloh
    TYPE_OF_ATTACHMENT = (
        ('audio', 'Audio'),
        ('image', 'Image'),
        ('text', 'Text'),
        ('video', 'Video'),
        ('other', 'Other'),
    )

    # Pole s definovanými předvolbami pro uložení typu přílohy
    type = models.CharField(max_length=5, choices=TYPE_OF_ATTACHMENT, blank=True, default='image',
                            help_text='Select allowed attachment type', verbose_name="Attachment type")
    # Cizí klíč, který zajišťuje propojení přílohy s daným filmem (vztah N:1)
    # Parametr on_delete slouží k zajištění tzv. referenční integrity - v případě odstranění filmu
    # budou odstraněny i všechny jeho přílohy (models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)

    # Metadata
    class Meta:
        # Primární seřazeno podle poslední aktualizace souborů, sekundárně podle typu přílohy
        # ordering = ["-last_update", "type"]
        order_with_respect_to = 'film'

    # Methods
    def __str__(self):
        """ Textová reprezentace objektu """
        return f"{self.title}, ({self.type})"

    @property
    def filesize(self):
        x = self.file.size
        y = 512000
        if x < y * 1000:
            value = round(x / 1024, 2)
            ext = ' KB'
        elif x < y * 1000 ** 2:
            value = round(x / 1024 ** 2, 2)
            ext = ' MB'
        else:
            value = round(x / 1024 ** 3, 2)
            ext = ' GB'
        return str(value) + ext

movies/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from movies.models import *


def index(request):
    """Metoda připravuje pohled pro domovskou stránku - šablona index.html"""

    # Uložení celkového počtu filmů v databázi do proměnné num_films
    num_films = Film.objects.all().count()
    # Do proměnné films se uloží 3 filmy uspořádané podle hodnocení (sestupně)
    films = Film.objects.order_by('-rate')[:3]

    """ Do proměnné context, která je typu slovník (dictionary) uložíme hodnoty obou proměnných """
    context = {
        'num_films': num_films,
        'films': films
    }

    """ Pomocí metody render vyrendrujeme šablonu index.html a předáme ji hodnoty v proměnné context k zobrazení """
    return render(request, 'index.html', context=context)


class FilmListView(ListView):
    model = Film

    context_object_name = 'film_list'
    template_name = 'film/list.html'
    paginate_by = 2

    def get_queryset(self):
        if 'genre_name' in self.kwargs:
            return Film.objects.filter(
                genres__name=self.kwargs['genre_name']).all()  # Get 5 books containing the title war
        else:
            return Film.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['num_films'] = len(self.get_queryset())
        if 'genre_name' in self.kwargs:
            context['view_title'] = f"Žánr: {self.kwargs['genre_name']}"
            context['view_head'] = f"Žánr filmu: {self.kwargs['genre_name']}"
        else:
            context['view_title'] = 'Filmy'
            context['view_head'] = 'Přehled filmů'
        return context


class FilmDetailView(DetailView):
    model = Film

    context_object_name = 'film_detail'
    template_name = 'film/detail.html'


def topten(request):
    return render(request, 'topten.html')

movies/templates/film/detail.html
{% extends "base.html" %}
{% block title %}Detail filmu{% endblock %}

{% block css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="row mb-3">
    <div class="col-sm-12 bg-warning">
        <h2 class="display-4 text-center">Podrobné informace</h2>
    </div>
</div>
<div class="row mt-5 mb-3">
    <div class="col-lg-6 mb-3">
        <h2 class="display-4 mb-3">{{ film_detail.title }}</h2>
        <div class="bg-secondary text-light p-2 mb-3">Rok vzniku: {{ film_detail.release_date.year }}, stopáž: {{ film_detail.runtime }} minut,
            {% with ''|center:film_detail.rate as range %}
            {% for _ in range %}★{% endfor %}
            {% endwith %}
            <b>{{ film_detail.rate }}</b>
        </div>
        <div class="row">
            <div class="col-md-9">{{ film_detail.plot }}</div>
            <div class="col-md-3">
                {% if film_detail.poster %}
                <a href="{{ film_detail.poster.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ film_detail.poster.url }}" class="img-fluid" alt="Plakát k filmu">
                </a>
                {% else %}
                <p class="alert alert-warning">Žádná příloha neexistuje</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg-6 bg-light p-3">
        <h3 class="border-bottom pb-3 text-secondary text-center text-uppercase">Fotogalerie</h3>
        <div class="row">
        {% for image in film_detail.attachment_set.all %}
            <div class="col-lg-6 col-xl-4">
                <a href="{{ image.file.url }}" data-toggle="lightbox" data-gallery="gallery">
                    <img src="{{ image.file.url }}" class="img-fluid img-thumbnail" alt="{{ image.title }}">
                </a>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js"></script>
<script>
    $(document).on("click", '[data-toggle="lightbox"]', function(event) {
        event.preventDefault();
        $(this).ekkoLightbox();
    });
</script>
{% endblock %}

movies/templates/film/list.html
{% extends "base.html" %}
{% load bootstrap_pagination %}

{% block title %}{{ view_title }}{% endblock %}

{% block content %}
<div class="row mt-3 mb-3 bg-warning p-3">
    <div class="col-sm-12">
        <h2 class="text-center">{{ view_head }}</h2>
    </div>
</div>
<div class="row">
    {% for film in film_list %}
    <div class="col-sm-4 col-xl-2">
        <div class="card">
            {% if film.poster %}
            <img class="card-img-top" src="{{ film.poster.url }}" alt="{{ film.title }}">
            {% endif %}
            <div class="card-body">
                <h4 class="card-title">{{ film.title }}</h4>
                <p class="card-text"><strong>Žánry:</strong> 
                {% for genre in film.genres.all %}{{ genre.name }}{% endfor %}
                </p>
                <p><strong>Hodnocení:</strong> {{ film.rate }}</p>
                <a href="{% url 'film_detail' film.pk %}" class="btn btn-primary">Podrobnosti</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class="row">
    <div class="col-sm-12">
        Celkový počet filmů: {{num_films}}
    </div>
</div>

{% if num_films > 0 %}
<div class="row">
    <div class="col-sm-12">
        {% bootstrap_paginate page_obj range=10 %}
    </div>
</div>
{% endif %}

{% endblock %}